version: '3.3'

services:
  # MYSQL Databases
  ratingDB:
    container_name: "18-db_rating"
    build:
      context: ./Database
      dockerfile: ratingDB.Dockerfile
    image: 18-rating_db_image
    environment:
      MYSQL_TCP_PORT: 8185
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 8185:3306
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    volumes:
      - rating_data:/var/lib/mysql
    networks:
      - assignment2bridge
  # Comment database
  commentDB:
    container_name: "18-db_comment"
    build:
      context: ./Database
      dockerfile: commentDB.Dockerfile
    image: 18-comment_db_image
    environment:
      MYSQL_TCP_PORT: 8186
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 8186:3306
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    volumes:
      - comment_data:/var/lib/mysql
    networks:
      - assignment2bridge
# Student database
  studentDB:
    container_name: "18-db_student"
    build:
      context: ./Database
      dockerfile: studentDB.Dockerfile
    image: 18-student_db_image
    environment:
      MYSQL_TCP_PORT: 8187
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 8187:3306
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    volumes:
      - student_data:/var/lib/mysql
    networks:
      - assignment2bridge
  # Tutor databse
  tutorDB:
    container_name: "18-db_tutor"
    build:
      context: ./Database
      dockerfile: tutorDB.Dockerfile
    image: 18-tutor_db_image
    environment:
      MYSQL_TCP_PORT: 8188
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 8188:3306
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    volumes:
      - tutor_data:/var/lib/mysql
    networks:
      - assignment2bridge
  # Frontend server
  frontend:
    container_name: 18-frontend_react
    depends_on:
      - ratingMS
      - commentMS
      - studentMS
      - tutorMS
      - ratingDB
      - commentDB
      - studentDB
      - tutorDB
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    image: 18-frontend_react_image
    ports:
      - 8180:3000
    stdin_open: true
    volumes:
      - node_modules:/app/node_modules
    networks:
      - assignment2bridge
    # deploy:
    #   restart_policy:
    #     condition: on-failure

  # Rating Microservice
  ratingMS:
    depends_on:
      - ratingDB
    build:
      context: ./Microservices/Rating
      dockerfile: rating.Dockerfile
    image: 18-rating_ms_image
    container_name: 18-ms_rating
    ports:
      - 8181:8181
    networks:
      - assignment2bridge

  # Comment Microservice
  commentMS:
    depends_on:
      - commentDB
    build:
      context: ./Microservices/Comment
      dockerfile: comment.Dockerfile
    image: 18-comment_ms_image
    container_name: 18-ms_comment
    ports:
      - 8182:8182
    networks:
      - assignment2bridge

  # Student Mocked Microservice
  studentMS:
    depends_on:
      - studentDB
    build:
      context: ./Microservices/Student
      dockerfile: student.Dockerfile
    image: 18-student_ms_image
    container_name: 18-ms_student
    ports:
      - 8183:8183
    networks:
      - assignment2bridge
      
  # Tutor Mocked Microservice
  tutorMS:
    depends_on:
      - tutorDB
    build:
      context: ./Microservices/Tutor
      dockerfile: tutor.Dockerfile
    image: 18-tutor_ms_image
    container_name: 18-ms_tutor
    ports:
      - 8184:8184
    networks:
      - assignment2bridge

volumes:
  rating_data: null
  comment_data: null
  student_data: null
  tutor_data: null
  node_modules: null

networks:
  assignment2bridge:
    driver: bridge

